pet_mvp/pets/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_not_required

from pet_mvp.pets.views import ApprovePetAdditionView, PetDetailView, PetEditView, PetAddView, PetDeleteView, \
    MarkingAddView, MarkingDetailsView, AddExistingPetView, GenerateShareTokenView, AcceptShareTokenView, \
    PetAccessHistoryView

urlpatterns = [
    path('add/', PetAddView.as_view(), name='pet-add'),
    path('add-existing/', AddExistingPetView.as_view(), name='pet-add-existing'),
    path('pets/approve/<str:token>/', login_not_required(ApprovePetAdditionView.as_view()),
         name='approve-pet-addition'),
    path('share/<uuid:token>/', AcceptShareTokenView.as_view(), name='accept-share-token'),
    path('<int:pk>/',
         include([
             path('details/', PetDetailView.as_view(), name='pet-details'),
             path('access-history/', PetAccessHistoryView.as_view(), name='pet-access-history'),
             path('edit/', PetEditView.as_view(), name='pet-edit'),
             path('delete/', PetDeleteView.as_view(), name='pet-delete'),
             path('marking/',
                  include([
                      path('add/', MarkingAddView.as_view(), name='marking-add'),
                      path('details/', MarkingDetailsView.as_view(),
                           name='marking-details')
                  ])),
             path('share/', GenerateShareTokenView.as_view(), name='generate-share-qr')
         ])
         )
]

pet_mvp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog
from django.contrib.sitemaps.views import sitemap
from pet_mvp.common.sitemaps import StaticViewSitemap
from django.contrib.auth.decorators import login_not_required
urlpatterns = [
    # For the set_language view
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('pet_mvp.common.urls')),
    path('access_codes/', include('pet_mvp.access_codes.urls')),
    path('accounts/', include('pet_mvp.accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('pet_mvp.api.urls')),
    path('pets/', include("pet_mvp.pets.urls")),
    path('records/',
         include([
             path('', include("pet_mvp.records.urls")),
             path('',
                  include("pet_mvp.drugs.urls")
                  )
         ])),
]

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns += [
    path('sitemap.xml', login_not_required(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_mvp/logs/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _

from pet_mvp.pets.models import Pet

UserModel = get_user_model()


class PetAccessLog(models.Model):

    pet = models.ForeignKey(
        to=Pet,
        on_delete=models.CASCADE
    )
    accessed_by = models.ForeignKey(
        to=UserModel,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('Accessed By')
    )
    access_time = models.DateTimeField(
        default=timezone.now,
        verbose_name=_('Access Time')
    )

    method = models.CharField(
        max_length=50,
        choices=[
            ('qr', 'QR Code'),
            ('link', _('Shared Link')),
            ('owner', _('Owner')),
            ('clinic', _('Clinic View')),
        ],
        default='owner',
        verbose_name=_('Access Method')
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)

    def __str__(self):
        return f"{self.pet.name} accessed by {self.accessed_by} via {self.method} at {self.access_time}"

pet_mvp/pets/views.py
from datetime import date
import qrcode
import base64
from io import BytesIO
from datetime import timedelta
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views import generic as views
from django.core.signing import Signer, BadSignature
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from django.contrib import messages

from pet_mvp.access_codes.models import QRShareToken, VetPetAccess
from pet_mvp.access_codes.utils import generate_access_code
from pet_mvp.logs.mixins import PetAccessLoggingMixin
from pet_mvp.logs.models import PetAccessLog
from pet_mvp.notifications.tasks import send_owner_pet_addition_request
from pet_mvp.pets.forms import AddExistingPetForm, PetAddForm, MarkingAddForm, PetEditForm
from pet_mvp.pets.models import Pet

UserModel = get_user_model()
signer = Signer()

class PetDetailView(PetAccessLoggingMixin, views.DetailView, ):
    model = Pet
    template_name = "pet/pet_details.html"

    def get(self, request, *args, **kwargs):

        if not request.user.is_owner:
            self.access_log_method = 'clinic'

        response = super().get(request, *args, **kwargs)
        pet = self.get_object()
        self.log_pet_access_once_per_session(request, pet)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get the pet
        pet = Pet.objects.get(pk=self.kwargs['pk'])

        # generate code
        user = self.request.user
        if user.is_owner:
            access_code = generate_access_code(pet)
            context['access_code'] = access_code.code

        context['valid_vaccinations'] = pet.vaccine_records.filter(valid_until__gte=date.today()).order_by(
            '-valid_until')
        context['valid_treatments'] = pet.medication_records.filter(valid_until__gte=date.today()).order_by(
            '-created_at')
        context['last_examinations'] = pet.examination_records.all().order_by(
            '-created_at')[:3]

        return context


class PetEditView(views.UpdateView):
    model = Pet
    template_name = "pet/pet_edit.html"
    form_class = PetEditForm

    def get_success_url(self):
        return reverse_lazy('pet-details', kwargs={'pk': self.object.pk})


class PetAddView(views.CreateView):
    model = Pet
    template_name = "pet/pet_add.html"
    form_class = PetAddForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dog_breeds'] = Pet.DOG_BREED_CHOICES
        context['cat_breeds'] = Pet.CAT_BREED_CHOICES
        return context

    def get_success_url(self):
        return reverse_lazy('dashboard')

    def form_valid(self, form):
        new_pet = form.save()
        new_pet.owners.add(self.request.user)

        return redirect('dashboard')


class AddExistingPetView(views.FormView):
    form_class = AddExistingPetForm
    template_name = 'pet/pet_add_existing.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        passport_number = form.cleaned_data['passport_number']

        try:
            pet = Pet.objects.get(passport_number=passport_number)
        except Pet.DoesNotExist:
            form.add_error('passport_number', _('Invalid passport number: no pet found with these details.'))
            return self.form_invalid(form)

        existing_owner = pet.owners.first()
        token = signer.sign(f'{pet.id}:{self.request.user.id}')
        approval_url = self.request.build_absolute_uri(
            reverse('approve-pet-addition', args=[token])
        )

        send_owner_pet_addition_request(
            existing_owner=existing_owner,
            new_owner=self.request.user,
            pet=pet,
            approval_url=approval_url
        )

        pet.pending_owners.add(self.request.user)
        messages.success(self.request, _(
            "Your request to access the pet has been sent to the owner."))

        return redirect(self.get_success_url())


class ApprovePetAdditionView(views.View):
    def get(self, request, token):
        try:
            data = signer.unsign(token)
            pet_id, user_id = map(int, data.split(':'))
            pet = Pet.objects.get(id=pet_id)
            user = UserModel.objects.get(id=user_id)

            pet.owners.add(user)
            pet.pending_owners.remove(user)

            context = {
                "pet_name": pet.name,
                "new_owner": user.get_full_name(),
            }
            return render(request, "pet/approve_confirmation.html", context)

        except (BadSignature, Pet.DoesNotExist, UserModel.DoesNotExist):
            return HttpResponseBadRequest(_('Invalid or expired link.'))


class PetDeleteView(views.DeleteView):
    model = Pet
    success_url = reverse_lazy('dashboard')
    template_name = 'pet/pet_delete.html'

    def form_valid(self, form):
        success_url = self.get_success_url()
        pet = self.object
        # if more than one owner - remove the user from the owners
        if len(pet.owners.all()) > 1:
            pet.owners.remove(self.request.user)

        # delete the pet otherwise
        else:
            self.object.delete()

        return HttpResponseRedirect(success_url)


    def get_object(self, queryset=None):
        return Pet.objects.get(pk=self.kwargs['pk'])


class MarkingAddView(views.FormView):
    template_name = 'pet/marking_add.html'
    form_class = MarkingAddForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pet'] = get_object_or_404(Pet, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        pet = get_object_or_404(Pet, pk=self.kwargs['pk'])
        self.object = form.save(pet=pet)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('pet-details', kwargs={'pk': self.kwargs['pk']})


class MarkingDetailsView(views.DetailView):
    template_name = 'pet/marking_details.html'

    def get_queryset(self):
        return Pet.objects.filter(pk=self.kwargs['pk'])

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pet = queryset.first()

        try:
            return pet.transponder
        except ObjectDoesNotExist:
            pass

        try:
            return pet.tattoo
        except ObjectDoesNotExist:
            return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pet_pk'] = self.kwargs['pk']

        return context


class GenerateShareTokenView(views.View):

    def get(self, request, pk):
        if not self.request.user.is_owner:
            messages.error(self.request, _("You must be an owner to generate a share link."))
            return redirect('index')

        pet = get_object_or_404(Pet, pk=pk)

        # Create or get token
        token_obj = QRShareToken.objects.create(pet=pet)
        token_url = request.build_absolute_uri(
            reverse('accept-share-token', kwargs={'token': token_obj.token})
        )

        # Generate QR code image
        qr = qrcode.make(token_url)
        buffer = BytesIO()
        qr.save(buffer, format="PNG")
        qr_base64 = base64.b64encode(buffer.getvalue()).decode()

        return render(request, "access_codes/pet_qr_share.html", {"qr_code_base64": qr_base64, "pet": pet})


class AcceptShareTokenView(views.RedirectView):

    def get_not_success_url(self):
        if self.request.user.is_owner:
            return reverse('dashboard')
        else:
            return reverse('clinic-dashboard')

    def get_redirect_url(self, *args, **kwargs):
        # extract the token
        token_str = self.kwargs['token']

        # verify token exists
        try:
            token = QRShareToken.objects.get(token=token_str)
        except QRShareToken.DoesNotExist:
            messages.error(self.request, _("Invalid or expired token."))
            return self.get_not_success_url()

        # verify token is valid
        if not token.is_valid():
            messages.error(self.request, _("This share link has expired or already been used."))
            return self.get_not_success_url()

        # get the pet associated with the token
        pet = token.pet
        user = self.request.user
        # logic for the current user, checking the code
        # owner - add the current user to an owner list
        if user.is_owner:
            pet.owners.add(self.request.user)

        # user is clinic - add the access to vetpet access model
        else:
            VetPetAccess.objects.update_or_create(
                vet=user,
                pet=pet,
                defaults={
                    'expires_at': timezone.now() + timedelta(minutes=10),
                    'granted_by': 'qr'
                }
            )
        token.used = True
        token.save()
        messages.success(self.request,
                         message=_("You now have access to %(pet_name)s's profile.") % {"pet_name": pet.name})
        return reverse('pet-details', kwargs={'pk': pet.id})


class PetAccessHistoryView(views.TemplateView):
    template_name = 'pet/access_history.html'
    model = PetAccessLog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pet = get_object_or_404(Pet, pk=self.kwargs['pk'])
        access_logs = PetAccessLog.objects.filter(pet=pet).order_by('-access_time')

        context['access_logs'] = access_logs
        context['source'] = self.request.GET.get('source')
        context['id'] = pet.id

        return context

templates/pet/access_history.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container mt-4 history-page-wrapper">
        <h3 class="mb-3">{% trans "Access History" %}</h3>

        <div class="table-responsive" style="max-height: 500px; overflow-y: auto;">
            <table class="table table-sm table-bordered mb-0">
                <thead class="table-light sticky-top">
                <tr>
                    <th>{% trans "Time" %}</th>
                    <th>{% trans "Accessed By" %}</th>
                    <th>{% trans "Method" %}</th>
                    <th>{% trans "IP" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for log in access_logs %}
                    <tr>
                        <td>{{ log.access_time|date:"d/m/Y H:i" }}</td>
                        <td>{{ log.accessed_by.get_full_name }}</td>
                        <td>{{ log.get_method_display }}</td>
                        <td>{{ log.ip_address }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center text-muted">{% trans "No access history yet." %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="mt-4">
            {% include 'partials/back_buttons.html' %}
        </div>
    </div>

{% endblock %}

templates/pet/approve_confirmation.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h2 class="mb-4 text-success">{% trans "Request Approved" %}</h2>
            <p>
                {% blocktrans with new_owner=new_owner pet_name=pet_name %}
                You have successfully approved {{ new_owner }} to access and manage the medical records for <strong>{{ pet_name }}</strong>.
                {% endblocktrans %}
            </p>
        </div>
    </div>
</section>
{% endblock %}

templates/pet/marking-details.html
{% extends 'base.html' %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="p-4 border rounded bg-light">
                <h3 class="mb-4">Marking Details</h3>

                <ul class="list-group mb-4">
                    <li class="list-group-item"><strong>Marking Type:</strong> {{ object.type }}</li>
                    <li class="list-group-item"><strong>Unique Code Identification:</strong> {{ object.code }}</li>
                    <li class="list-group-item"><strong>Location of the Marking:</strong> {{ object.location }}</li>
                    <li class="list-group-item"><strong>Date of Application:</strong> {{ object.date_of_application }}</li>
                </ul>

                <a href="{% url 'pet-details' pk=pet_pk %}" class="btn btn-secondary">Back to Pet's Details</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/pet/marking_add.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="mb-4 text-center">{% trans "Add Marking" %}</h2>

            <form action="{% url 'marking-add' pk=pet.pk %}" method="post" class="p-4 border rounded bg-light">
                {% csrf_token %}

                {% for field in form %}
                    <div class="mb-3">
                        {{ field.label_tag }}
                        {{ field|add_class:"form-control" }}
                        {% if field.help_text %}
                            <div class="form-text">{{ field.help_text|safe }}</div>
                        {% endif %}
                        {% for error in field.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endfor %}

                <div class="d-flex flex-wrap gap-2 justify-content-between mt-4">
                    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                    <button type="reset" class="btn btn-outline-secondary">{% trans "Reset" %}</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/pet/marking_details.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="p-4 border rounded bg-light">
                <h3 class="mb-4">{% trans "Marking Details" %}</h3>

                <ul class="list-group mb-4">
                    <li class="list-group-item"><strong>{% trans "Marking Type:" %}</strong> {{ object.type }}</li>
                    <li class="list-group-item"><strong>{% trans "Unique Code Identification:" %}</strong> {{ object.code }}</li>
                    <li class="list-group-item"><strong>{% trans "Location of the Marking:" %}</strong> {{ object.location }}</li>
                    <li class="list-group-item"><strong>{% trans "Date of Application:" %}</strong> {{ object.date_of_application }}</li>
                </ul>

                <a href="{% url 'pet-details' pk=pet_pk %}" class="btn btn-secondary">{% trans "Back to Pet's Details" %}</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/pet/pet-delete.html
{% extends "base.html" %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="p-4 border rounded bg-light text-center">
                <h2 class="mb-4 text-danger">Confirm Deletion</h2>
                <p class="mb-4">Are you sure you want to delete <strong>{{ object }}</strong>?</p>

                <form action="{% url 'pet-delete' pk=object.pk %}" method="post">
                    {% csrf_token %}

                    <div class="d-grid gap-2 d-md-flex justify-content-center">
                        <button type="submit" class="btn btn-danger">Yes, Delete</button>
                        <a href="{% url 'pet-details' pk=object.pk %}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/pet/pet_add.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load i18n %}
{% block content %}
    <section class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2 class="mb-4 text-center">{% trans "Add a New Pet" %}</h2>
                <div class="alert alert-info text-center mb-4" role="alert">
                    <p class="mb-2">
                        {% trans "If your pet has already been registered by a veterinarian or another caregiver, you can request access to its medical records using its passport number." %}
                    </p>
                    <p class="mb-3">
                        {% trans "Use this option only if you are sure the pet already exists in the system and is registered with a passport. Otherwise, please continue with the form below to register a new pet." %}
                    </p>
                    <a href="{% url 'pet-add-existing' %}"
                       class="btn btn-primary">{% trans "Request access to an existing pet" %}</a>
                </div>
                {% if messages %}
                    <div class="mb-3">
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                                 role="alert">
                                {{ message }}
                                <button type="button"
                                        class="btn-close"
                                        data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {% trans "Select species" as select_species_label %}
                {% trans "Select gender" as select_gender_label %}
                {% trans "Select breed" as select_breed_label %}
                <div class="alert alert-info mb-4" role="alert">
                    <h5 class="alert-heading">{% trans "Multilingual Field Notice" %}</h5>
                    <p>
                        {% trans "Please enter all fields that end with 'in English' and 'in Bulgarian'. This helps us ensure proper language support for both local and international use." %}
                    </p>
                    <hr>
                    <p class="mb-0">
                        {% trans "These fields will appear in different parts of the application depending on the user's language preference." %}
                    </p>
                </div>
                <div class="alert alert-info mb-4" role="alert">
                    <h5 class="alert-heading">{% trans "Passport Field Notice" %}</h5>
                    <p>
                        {% trans "The passport number field could be left blank if the animal has no passport issued. However, if the passport number is not available, the options of adding co-owners will be limited." %}
                    </p>
                </div>
                <form action="{% url 'pet-add' %}"
                      method="post"
                      enctype="multipart/form-data"
                      class="p-4 border rounded bg-light">
                    {% csrf_token %}
                    {# Move passport_number to top #}
                    {% if form.passport_number %}
                        <div class="mb-3">
                            <label for="{{ form.passport_number.id_for_label }}"
                                   class="form-label">{{ form.passport_number.label }}</label>
                            {{ form.passport_number|add_class:"form-control" }}
                            {% if form.passport_number.help_text %}
                                <div class="form-text">{{ form.passport_number.help_text|safe }}</div>
                            {% endif %}
                            {% for error in form.passport_number.errors %}
                                <div class="text-danger">{{ error }}</div>{% endfor %}
                        </div>
                    {% endif %}
                    {# Render remaining fields #}
                    {% for field in form %}
                        {% if field.name != 'passport_number' %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field|add_class:"form-control" }}
                                {% if field.help_text %}
                                    <div class="form-text">{{ field.help_text|safe }}</div>{% endif %}
                                {% for error in field.errors %}
                                    <div class="text-danger">{{ error }}</div>{% endfor %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="d-flex flex-wrap gap-2 justify-content-between mt-4">
                        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                        <button type="reset" class="btn btn-outline-secondary">{% trans "Reset" %}</button>
                        <a href="{% url 'dashboard' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <script>
        const SELECT_SPECIES_LABEL = "{{ select_species_label }}";
        const SELECT_GENDER_LABEL = "{{ select_gender_label }}";
        const SELECT_BREED_LABEL = "{{ select_breed_label }}";

        document.addEventListener('DOMContentLoaded', function () {
            const speciesSelect = document.getElementById('id_species');
            speciesSelect.options[0].text = SELECT_SPECIES_LABEL
            speciesSelect.options[0].value = '';

            const genderSelect = document.getElementById('id_sex')
            genderSelect.options[0].text = SELECT_GENDER_LABEL
            genderSelect.options[0].value = '';

            const breedSelect = document.getElementById('id_breed');

            const dogBreeds = [
                    {% for value, label in dog_breeds %}['{{ value }}', '{{ label }}'],{% endfor %}
            ];

            const catBreeds = [
                    {% for value, label in cat_breeds %}['{{ value }}', '{{ label }}'],{% endfor %}
            ];


            function updateBreedChoices() {
                breedSelect.innerHTML = '';

                const defaultOption = document.createElement('option');
                defaultOption.value = '';
                defaultOption.textContent = SELECT_BREED_LABEL;
                breedSelect.appendChild(defaultOption);

                const selectedSpecies = speciesSelect.value;
                let breeds = [];

                if (selectedSpecies === 'dog') {
                    breeds = dogBreeds;
                } else if (selectedSpecies === 'cat') {
                    breeds = catBreeds;
                }

                breeds.forEach(function (breed) {
                    const option = document.createElement('option');
                    option.value = breed[0];
                    option.textContent = breed[1];
                    breedSelect.appendChild(option);
                });
            }

            speciesSelect.addEventListener('change', updateBreedChoices);
            updateBreedChoices();
        });
    </script>
{% endblock %}

templates/pet/pet_add_existing.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">

            <!-- 🔗 Info about Pet Share QR -->
            <div class="alert alert-info mb-4" role="alert">
                <h5 class="alert-heading">{% trans "Got a Share QR Code?" %}</h5>
                <p>{% trans "If the pet owner sent you a QR code or a link, you can scan or open it to instantly gain access to the pet — no need to fill out this form." %}</p>
                <hr>
                <p class="mb-0 text-muted">{% trans "This form is only needed if you're requesting access by passport number instead." %}</p>
            </div>

            <h2 class="mb-4 text-center">{% trans "Request Access to Existing Pet" %}</h2>

            <form method="post" class="p-4 border rounded bg-light">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.passport_number.label_tag }}
                    {{ form.passport_number|add_class:"form-control" }}
                    {% for error in form.passport_number.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                    {% if form.passport_number.help_text %}
                        <div class="form-text">{{ form.passport_number.help_text }}</div>
                    {% endif %}
                </div>

                <div class="d-flex flex-wrap gap-2 justify-content-between mt-4">
                    <button type="submit" class="btn btn-primary">{% trans "Send Request" %}</button>
                    <a href="{% url 'dashboard' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/pet/pet_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="p-4 border rounded bg-light text-center">
                <h2 class="mb-4 text-danger">{% trans "Confirm Deletion" %}</h2>
                <p class="mb-4">{% trans "Are you sure you want to delete" %} <strong>{{ object }}</strong>?</p>

                <form action="{% url 'pet-delete' pk=object.pk %}" method="post">
                    {% csrf_token %}

                    <div class="d-grid gap-2 d-md-flex justify-content-center">
                        <button type="submit" class="btn btn-danger">{% trans "Yes, Delete" %}</button>
                        <a href="{% url 'pet-details' pk=object.pk %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}